
default: &default
  adapter: postgresql
  encoding: unicode
  timeout: 5000
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Todo_app_development

  
test:
  <<: *default
  database: Todo_app_test

production:
  <<: *default
  database: Todo_app_production
  username: Todo_app
  password: <%= ENV['DATABASE_PASSWORD'] %>
  host: <%= ENV['DATABASE_HOST'] %>
